### ISSUE TITLE
Move ConstraintViolationProblem to problem library

### ISSUE THREAD

**Issue by Tomschi** [zalando/problem-spring-web#112]
Is there any reason, why ConstraintViolationProblem is not placed in problem library?
On client side, i only use problem library to avoid spring dependency conflicts. Without ConstraintViolationProblem in problem library i have the check parameters, if current ThrowableProblem is a ConstraintViolationProblem.

**Comment by whiskeysierra** [comment]
> On client side

If you read the [definition](http://zalando.github.io/problem/constraint-violation/) of what we intended this problem type to be:

> It’s not meant to be used for end-user input validation, but for client developer convenience.

So there should be no reason to read this on the client side, at least not in a typed/automatic fashion. This problem is meant to indicate a bug, nothing that clients should put any semantic in.

Since this problem type is not meant to be deserialized, I didn't feel the need to define the class in the problem library and rather treat it as an implementation detail of the server-side library.

**Comment by whiskeysierra** [comment]
@Tomschi I'll close this for now. Feel free to open it again if you disagree.
