### ISSUE TITLE
Can't deserialize ConstraintViolationProblem

### ISSUE THREAD

**Issue by henri-tremblay** [zalando/problem-spring-web#115]
It seems that a `ConstraintViolationProblem` can be serialized but fails to be deserialized. Because Jackson always tried to use a `DefaultProblem`.

Here is a short example:

```java
@Configuration
public class App {

    public static void main(String[] args) throws Exception {
        ApplicationContext context = new AnnotationConfigApplicationContext(App.class);
        ObjectMapper objectMapper = context.getBean(ObjectMapper.class);
        ConstraintViolationProblem problem = new ConstraintViolationProblem(Status.BAD_REQUEST, Arrays.asList(new Violation("login", "too short")));
        byte[] b = objectMapper.writeValueAsBytes(problem);
        problem = objectMapper.readValue(b, ConstraintViolationProblem.class);
    }

    @Bean
    public ObjectMapper objectMapper() {
        return new ObjectMapper()
            .registerModule(new ProblemModule())
            .registerModule(new ConstraintViolationProblemModule());
    }
}
```

Running it will cause the following exception:

> Exception in thread "main" java.lang.IllegalArgumentException: Class org.zalando.problem.DefaultProblem not subtype of [simple type, class org.zalando.problem.spring.web.advice.validation.ConstraintViolationProblem]
> 	at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:359)
> 	at com.fasterxml.jackson.databind.jsontype.impl.StdTypeResolverBuilder.buildTypeDeserializer(StdTypeResolverBuilder.java:128)
> 	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findTypeDeserializer(BasicDeserializerFactory.java:1372)
> 	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:482)
> 	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3915)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3810)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2945)
> 	at com.mycompany.App.main(App.java:29)

It feels like something is wrong in the jackson configuration.

**Comment by whiskeysierra** [comment]
As stated by http://zalando.github.io/problem/constraint-violation/:

> It’s not meant to be used for end-user input validation, but for client developer convenience. Any constraint violation problem happening in production should be considered a bug.

I.e., you shouldn't deserialize it, since you shouldn't handle it automatically. If you have wire-logging in place (hint, hint https://github.com/zalando/logbook), you can see everything you need in your logs. Even if you log the deserialized DefaultProblem, you should see everything (since it implements toString).

**Comment by whiskeysierra** [comment]
Feel free to re-open this, if you have some more arguments/thoughts/ideas.

**Comment by henri-tremblay** [comment]
What I don't get is why `ProblemHandling` has a `ValidationAdviceTrait` is constraint are made to be on the client side?

**Comment by whiskeysierra** [comment]
What do you mean?

**Comment by henri-tremblay** [comment]
I mean the `ConstraintViolationAdviceTrait` seems to be made to transform a Spring validation error into a `ConstraintViolationProblem` with violations. To be used on the server side to send errors to the clients.

So, we are then saying it should not be used on the client side. So far so good.

Where I am now lost is if I read #118. Which seem to say that is was meant to be used on the client side. So I am a bit lost here.

**Comment by whiskeysierra** [comment]
I made the same argument in #118. I see three possibilities:

1. Change the semantics of the constraint violation problem to allow for end-user input validation. Since this is not my area of expertise, I'm not sure whether the general structure even supports more sophisticated use cases, e.g. l10n etc.
2. We stay with the current semantics and let clients implement their own problem. (The current, implicit strategy.)
3. We stay with the current semantics but invent another type of problem that allows for end-user input validation and let clients of the library choose which one they want to use.
