### ISSUE TITLE
JAR missing on Maven Central for problem-spring-web-starter 0.25.0

### ISSUE THREAD

**Issue by jbaiter** [zalando/problem-spring-web#378]
## Description
When including the `problem-spring-web-starter` artifact in the Maven configuration, building a project fails since there is no JAR in Maven Central for this version:

```xml
<dependency>
  <groupId>org.zalando</groupId>
  <artifactId>problem-spring-web-starter</artifactId>
  <version>0.25.0</version>
</dependency>
```

```
$ mvn clean install
...
Downloading from central: https://repo.maven.apache.org/maven2/org/zalando/problem-spring-web-starter/0.25.0/problem-spring-web-starter-0.25.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.565 s
[INFO] Finished at: 2019-10-14T15:05:48+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project *myproject*: Could not resolve dependencies for project *somegroup*:*myproject*:jar:3.2.0-SNAPSHOT: Could not find artifact org.zalando:problem-spring-web-starter:jar:0.25.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

## Expected Behavior
There should be a JAR for this version on Maven Central.

## Actual Behavior
There is not JAR on Maven Central for this version, only a POM:
https://repo1.maven.org/maven2/org/zalando/problem-spring-web-starter/0.25.0/

## Possible Fix
Deploy a JAR to Maven Central?

**Comment by theHilikus** [comment]
My bad. It seems in the IDE the dependency can be found even with the wrong packaging. That's why I didn't notice. As a workaround, you can depend on the pom itself, since the starter jar is empty anyway. This is just a workaround because it's not the spring-boot convention, but it works

        <dependency>
            <groupId>org.zalando</groupId>
            <artifactId>problem-spring-web-starter</artifactId>
            <version>0.25.0</version>
            <type>pom</type>
        </dependency>
Notice the "type" element

**Comment by whiskeysierra** [comment]
Good catch! Would you be willing to prepare a pull request to remove the type `pom` from the starter (effectively changing it to jar)?

**Comment by theHilikus** [comment]
yes. i looked into it yesterday but i remembered that the reason why I made it a pom is that when it is a jar, the build fails because there's a bunch of repeated classes in the classpath and there's a plugin checking that. I'm not sure how to go about this. I can either disable the plugin for this submodule, or i can start excluding the duplicated dependencies, but this seems to go against the whole point of a starter, which is to pull all the dependencies that are needed to use the library that it is starting. what do you think?

**Comment by whiskeysierra** [comment]
See https://github.com/zalando/problem-spring-web/pull/382
