### ISSUE TITLE
Support AccessDeniedException

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#73]
`AccessDeniedException` is common exception from Spring security when trying to access to authorize API but without any authentication or anonymous (and maybe others).

I know `problem-spring-web` is like a framework but it should at least support basic/common *Spring security* exception?

Expected:

- **status**: `401`

**Comment by whiskeysierra** [comment]
According to https://en.wikipedia.org/wiki/List_of_HTTP_status_codes I'd suggest to use:

**401 Unauthorized for AuthenticationException**

> 401 semantically means "unauthenticated"

> The 401 (Unauthorized) status code indicates that the request has not
   been applied because it lacks valid authentication credentials for
   the target resource.

https://tools.ietf.org/html/rfc7235#section-3.1

**403 Forbidden for AccessDeniedException**

> The user might be logged in but does not have the necessary permissions for the resource.

The naming of the http status codes is unfortunate, but I think this is the more correct fit.

**Comment by kakawait** [comment]
@whiskeysierra (I have to confirm it) but Spring is throwing `AccessDeniedException` even if you do not pass any auth (so `401`).

I will try to create a demo app to show the case and how can we handle choice between `401` (if no authentication credentials) and `403`

**Comment by whiskeysierra** [comment]
> (I have to confirm it) but Spring is throwing AccessDeniedException even if you do not pass any auth (so 401).

Correct, but if you're anonymous this exception will be delegated to the AuthenticationEntryPoint as an AuthenticationException.

Take a look at #75 I have a test for both cases.

**Comment by whiskeysierra** [comment]
@kakawait See https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/access/ExceptionTranslationFilter.java#L159

**Comment by kakawait** [comment]
@whiskeysierra ok nice, sorry I didn't check the code when I was written.
